Repository ant-design/ant-design-pro-layout, pull requests merged in 2019-12, with the labels that each got.

#212 fix: breadcrumb order and route config do not match
  src/BasicLayout.tsx
  src/getPageTitle.ts
  src/utils/getBreadcrumbProps.tsx
  src/utils/getMenuData.ts
Labels: bug

#224 feat: add tabAnimated props
  .stories/index.stories.tsx
  src/PageHeaderWrapper/index.tsx
Labels: enhancement

#241 bugifx: fix mobile menu
  src/SiderMenu/index.tsx
Labels: bugifx

#238 feat: decoupling item path
  example/src/layouts/BasicLayout.tsx
  package.json
  src/BasicLayout.tsx
  src/SiderMenu/BaseMenu.tsx
  src/SiderMenu/Counter.ts
  src/SiderMenu/SiderMenu.tsx
  src/SiderMenu/SiderMenuUtils.ts
  src/SiderMenu/index.tsx
  src/TopNavHeader/index.tsx
  src/getPageTitle.ts
  src/typings.ts
  src/utils/getMenuData.ts
  src/utils/utils.ts
  tests/__tests__/__snapshots__/index.test.tsx.snap
  tests/__tests__/__snapshots__/pageHeaderWarp.test.tsx.snap
Labels: enhancement

#243 bugfix: fix the problem that the top menu bar is not responsive
  example/config/config.ts
  src/BasicLayout.less
  src/TopNavHeader/index.tsx
Labels: BugFix

#244 feat: improved access to menu keys
  README.md
  README.zh-CN.md
  example/config/config.ts
  example/package.json
  example/src/layouts/BasicLayout.tsx
  example/src/pages/FormAdvancedForm/_mock.ts
  example/src/pages/FormAdvancedForm/components/FooterToolbar/index.less
  example/src/pages/FormAdvancedForm/components/FooterToolbar/index.tsx
  example/src/pages/FormAdvancedForm/components/TableForm.tsx
  example/src/pages/FormAdvancedForm/index.tsx
  example/src/pages/FormAdvancedForm/model.ts
  example/src/pages/FormAdvancedForm/service.ts
  example/src/pages/FormAdvancedForm/style.less
  package.json
  src/BasicLayout.less
  src/BasicLayout.tsx
  src/SiderMenu/BaseMenu.tsx
  src/SiderMenu/SiderMenuUtils.ts
  src/SiderMenu/index.tsx
  src/defaultSettings.ts
  src/typings.ts
  src/utils/getMenuData.ts
  src/utils/utils.ts
Labels: enhancement

#246 bugfix: fix settingDrawer no work for url params
  README.md
  README.zh-CN.md
  example/src/layouts/BasicLayout.tsx
  package.json
  src/GlobalHeader/index.tsx
  src/SettingDrawer/LayoutChange.tsx
  src/SettingDrawer/index.tsx
  src/SiderMenu/BaseMenu.tsx
  src/defaultSettings.ts
  src/utils/getMenuData.ts
  src/utils/utils.ts
  tests/__tests__/__snapshots__/settingDrawer.test.tsx.snap
  tests/__tests__/index.test.tsx
  tests/__tests__/pageHeaderWarp.test.tsx
  tests/__tests__/settingDrawer.test.tsx
  tests/__tests__/settings.test.tsx
  tests/__tests__/util.ts
Labels: BugFix

#249 bugfix: add fixedHeader test
  src/BasicLayout.tsx
  src/Header.tsx
  tests/__tests__/index.test.tsx
Labels: BugFix
