Repository ant-design/ant-design-pro-layout, pull requests merged in 2019-11, with the labels that each got.

#151 add: add bothmenu layout, with header and sider navigation(#65)
  README.md
  example/src/components/GlobalHeader/RightContent.tsx
  example/src/layouts/BasicLayout.tsx
  src/BasicLayout.tsx
  src/GridContent/index.tsx
  src/Header.tsx
  src/SiderMenu/BaseMenu.tsx
  src/SiderMenu/SiderMenu.tsx
  src/SiderMenu/index.less
  src/TopNavHeader/index.tsx
  src/defaultSettings.ts
Labels: add

#157 🙇‍♂️ 🙇‍♂️ 🙇‍♂️ Revert "add: add bothmenu layout, with header and sider navigation(#65)"
  README.md
  example/src/components/GlobalHeader/RightContent.tsx
  example/src/layouts/BasicLayout.tsx
  src/BasicLayout.tsx
  src/GridContent/index.tsx
  src/Header.tsx
  src/SiderMenu/BaseMenu.tsx
  src/SiderMenu/SiderMenu.tsx
  src/SiderMenu/index.less
  src/TopNavHeader/index.tsx
  src/defaultSettings.ts
Labels: add

#158 ✨ feat: support new props contentStyle
  src/BasicLayout.less
  src/BasicLayout.tsx
  src/SiderMenu/SiderMenu.tsx
  tests/__tests__/__snapshots__/index.test.tsx.snap
  tests/__tests__/index.test.tsx
Labels: enhancement

#160 ✨ feat: Support disable breakpoint
  README.md
  README.zh-CN.md
  example/src/layouts/BasicLayout.tsx
  src/SiderMenu/SiderMenu.tsx
Labels: enhancement

#159 ✨ feat: Nested layout
  .stories/index.stories.tsx
  example/src/layouts/BasicLayout.tsx
  src/BasicLayout.less
  src/BasicLayout.tsx
  src/GridContent/index.tsx
  src/Header.tsx
  src/PageHeaderWrapper/index.tsx
  src/RouteContext.tsx
  src/SiderMenu/index.less
  src/TopNavHeader/index.less
  src/TopNavHeader/index.tsx
  tests/__tests__/__snapshots__/index.test.tsx.snap
  tests/__tests__/__snapshots__/pageHeaderWarp.test.tsx.snap
Labels: enhancement

#164 :zap: 暴露TopNavHeader组件
  src/index.tsx
Labels: zap

#169 ✨ feat: all component support style and className
  example/src/typings.d.ts
  src/BasicLayout.tsx
  src/Footer.tsx
  src/GlobalFooter/index.tsx
  src/GlobalHeader/index.tsx
  src/GridContent/index.tsx
  src/Header.tsx
  src/PageHeaderWrapper/index.tsx
  src/SiderMenu/SiderMenu.tsx
  src/SiderMenu/index.tsx
  src/TopNavHeader/index.tsx
Labels: enhancement

#209 feat: rm autoHideHeader and fix fixedHeader problem
  README.md
  README.zh-CN.md
  example/config/defaultSettings.ts
  example/src/pages/Welcome.tsx
  src/BasicLayout.less
  src/Header.tsx
  src/SettingDrawer/index.tsx
  src/defaultSettings.ts
  tests/__tests__/__snapshots__/settingDrawer.test.tsx.snap
  tests/__tests__/defaultSettings.ts
Labels: enhancement
